### ISSUE TITLE
Creating a cluster with num_workers fails (workaround: autoscale)

### ISSUE THREAD

**Issue by mikemowgli** [innovationnorway/terraform-provider-databricks#49]
@joakimhellum , I had another problem than yesterday with the same config. I compiled your fix from yesterday about the int32, and now I'm running into this message. Once again, using autoscale is a workaround.

### Terraform Version
0.12

### Affected Resource(s)
databricks_cluster

### Terraform Configuration Files
```hcl
resource "databricks_cluster" "data-test" {
  cluster_name  = var.rg-name
  spark_version = var.databricks-version
  node_type_id  = var.databricks-node-size
  driver_node_type_id  = var.databricks-node-size
  num_workers   = var.databricks-num-workers

  spark_conf = {
    "spark.databricks.delta.preview.enabled" = true
  }
  autotermination_minutes = var.databricks-termination-delay
}
```
 `var.databricks-num-workers` is 1

### Panic Output
```
databricks_cluster.data-test: Creating...

Error: unable to create cluster: clusters.BaseClient#Create: Failure responding to request: StatusCode=400 -- Original Error: ErrorCode="BAD_REQUEST" Message="Current organization XXXX does not have any associated worker environments"

  on databricks.tf line 15, in resource "databricks_cluster" "data-test":
  15: resource "databricks_cluster" "data-test" {
```

### Expected Behavior
Cluster created

### Actual Behavior
Error message received

### Steps to Reproduce
 `terraform apply`

**Comment by joakimhellum** [comment]
@mikemowgli Thanks for reporting this issue!

I managed to reproduce this error message only when using `databricks_cluster` resource:

```
Current organization XXXX does not have any associated worker environments
```

Currently I'm not able to reproduce this error for other resources (like `databricks_group` and `databricks_workspace_import`).

This seems to be some internal Azure Databricks error where the environment it not always immediately ready after creation of Azure Databricks workspace. Retrying `terraform apply` after a few seconds seems to be working. Is this your experience also?

A suggested workaround is to retry cluster creation on this specific error message: `Current organization XXXX does not have any associated worker environments`.

Have created support ticket in Azure portal to request more information about this error message, since we cannot find anything in the official docs regarding this.

We aim to implement a fix (or the suggested workaround) within next few days. We will keep you posted.

Thanks again for reporting issues 🥰

**Comment by mikemowgli** [comment]
I confirm this behavior. Trying later indeed gets rid of the error.

**Comment by joakimhellum** [comment]
@mikemowgli Cool, many thanks! Then we will implement the suggested workaround during weekend, since I did not get feedback from Azure teams/Microsoft yet.
